# Generated by Django 2.2.12 on 2021-07-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20210714_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('email', models.CharField(max_length=10, unique=True, verbose_name='Correo')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Provider',
                'ordering': ['id'],
            },
        ),
    ]
