# Generated by Django 2.2.12 on 2021-07-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20210714_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timelimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Título')),
                ('dias', models.IntegerField(blank=True, null=True, verbose_name='Plazo de Pago')),
                ('tipo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tiempo Diferido')),
            ],
            options={
                'verbose_name': 'Timelimit',
                'verbose_name_plural': 'Timelimit',
                'ordering': ['id'],
            },
        ),
    ]
